Settings:
  Landing:
    TargetAtSpawn: false
  Portal:
    TargetServerName: 'anotherServer'
    CreationItems:
      - APPLE
    Flowers:
      - DANDELION
      - POPPY
      - BLUE_ORCHID
      - ALLIUM
      - AZURE_BLUET
      - ORANGE_TULIP
      - PINK_TULIP
      - RED_TULIP
      - WHITE_TULIP
      - POTTED_ORANGE_TULIP
      - POTTED_PINK_TULIP
      - POTTED_RED_TULIP
      - POTTED_WHITE_TULIP
      - OXEYE_DAISY
      - CORNFLOWER
      - LILY_OF_THE_VALLEY
      - WITHER_ROSE
      - SUNFLOWER
      - LILAC
      - ROSE_BUSH
      - PEONY
      - BROWN_MUSHROOM
      - RED_MUSHROOM
      - POTTED_BROWN_MUSHROOM
      - POTTED_RED_MUSHROOM